---
title: "Assessing far UVC interventions with an individual based infectious disease model"
author:
  - Charlie Whittaker^[Imperial College London], Tom Brewer^[Imperial College London], Adam Howes^[Independent]
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{blueprint}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: REFERENCES.bib
---

```{r, include = FALSE}
options(rmarkdown.html_vignette.check_title = FALSE)

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Abstract

`helios` is an R package implementing a stochastic individual based model of infectious disease transmission.
The package can be used to quantify the impact of installing far UVC interventions on epidemic outcomes such as infections and deaths.
The effectiveness of possible intervention implementations may be evaluated in order to guide development of far UVC technologies.

## Background

What is far UVC.

## Model description

The model consists of a fixed population of individuals.
Each individual is either a child, an adult or an elderly person.
During each day, individuals visit particular locations and mix with other individuals.
Disease transmission occurs stochastically between individuals in the same location.

The locations included in the model are households, schools, workplaces, and leisure venues.
Households compositions are based on...
Schools are attended by all children, with their sizes based on...
Workplaces are attended by all adults, with their sizes based on...
Something about leisure venues.
Something about how long people spend in each location.

At any time, each individual is either susceptible, exposed, infectious, or recovered.
Susceptible individuals become exposed after spending time with infectious individuals.
Time spent by individuals in each location and their level of risk is implemented by setting specific force of infection parameters.
Exposed individuals become infectious after some delay.
Infectious individuals become recovered after some delay.
Once recovered, individuals cannot be infected again.

Far UVC interventions can be installed in settings.
Remains to detail.

## Example model outputs

## Parameter sensitivity

## Bibliography {-}
