#' Generate a list of the model events and add listeners. Listeners are arbitrary functions called
#' when the event is fired with the current time step, t, as their only arguments.
#'
#' @param parameters A list of the model parameters as generated by `get_parameters`
#' @param variables A list of the model variables as generated by `create_variables`
#'
#' @export
create_events <- function(parameters, variables) {

  # Open a list to store the model events and populate using the event generator functions:
  events <- list(

    # Event moving exposed individuals to the infectious state
    EI_event = TargetedEvent$new(population_size = parameters$human_population),

    # Event moving exposed individuals to the infectious state
    IR_event = TargetedEvent$new(population_size = parameters$human_population)

  )

  # Add listener to the EI event:
  events$EI_event$add_listener(
    function(t, target) {
      variables$disease_state$queue_update("I", target)
    }
  )

  # Add listener to the IR event:
  events$IR_event$add_listener(
    function(t, target) {
      variables$disease_state$queue_update("R", target)
    }
  )

  # Return the list of model events:
  events
}
