# Standalone file: do not edit by hand
# Source: https://github.com/reside-ic/reside.utils/blob/strict-list/R/standalone-strict-list.R
# Generated by: usethis::use_standalone("reside-ic/reside.utils", "strict-list", ref = "strict-list")
# ----------------------------------------------------------------------
#
# ---
# repo: reside/reside.utils
# file: standalone-strict-list.R
# dependencies: standalone-utils-assert.R
# imports: cli
# ---

#' Create a named list with strict checks. 
#'
#' Accessing an unknown name (using any of `$`, `[` or `[[`) will throw an error
#' rather than return NULL.
#'
#' @param ... the named values used to construct the list
#' @param .name an optional description for the list, used in error messages
strict_list <- function(..., .name = NULL) {
  as_strict_list(list(...), name = .name)
}


#' Convert an existing named list into a strict one.
#' @param obj the existing named list
#' @param name an optional description for the list, used in error messages
as_strict_list <- function(obj, name = NULL) {
  assert_list(obj)
  if (length(obj) > 0) {
    assert_named(obj, unique = TRUE)
  }
  class(obj) <- c("strict_list", "list")
  attr(obj, "name") <- name %||% "list"
  obj
}

#' @export
as.list.strict_list <- function(x, ...) {
  class(x) <- NULL
  attr(x, "name") <- NULL
  x
}

#' @export
"[[.strict_list" <- function(x, i, ..., call = parent.frame()) {
  if (is.character(i) && !(i %in% names(x))) {
    name <- attr(x, "name")
    cli::cli_abort("'{i}' is not found in '{name}'", call = call)
  }
  unclass(x)[[i]]
}


#' @export
"$.strict_list" <- function(x, name, ..., call = parent.frame()) {
  x[[name, call = call]]
}


#' @export
"[.strict_list" <- function(x, i, ..., call = parent.frame()) {
  name <- attr(x, "name")
  if (is.character(i)) {
    msg <- setdiff(i, names(x))
    if (length(msg) > 0) {
      msg <- sprintf("'%s'", msg)
      cli::cli_abort("{msg} not found in '{name}'", call = call)
    }
  }
  ret <- unclass(x)[i]
  class(ret) <- class(x)
  attr(ret, "name") <- name
  ret
}
