#' Run the simulation
#'
#' @param parameters_list A list of model parameters as generated by [get_parameters()]
#' @param state Optional simulation state from a previous run, as returned in the
#'   `state` element of the output list. When provided, the simulation resumes from
#'   this state. `simulation_time` controls the number of *additional* timesteps to
#'   run (not the absolute end time). Default is `NULL` (start fresh).
#'
#' @return A list with two elements:
#'   \describe{
#'     \item{result}{A data frame of simulation outputs with one row per
#'       timestep. The columns are described below.}
#'     \item{state}{The final simulation state, which can be passed to a subsequent
#'       call to resume the simulation.}
#'   }
#'
#' The \code{result} data frame always contains the following columns:
#'   \itemize{
#'     \item \code{timestep}: The simulation timestep index.
#'     \item \code{S_count}: The number of individuals in the Susceptible
#'       disease state.
#'     \item \code{E_count}: The number of individuals in the Exposed (infected
#'       but not yet infectious) disease state.
#'     \item \code{I_count}: The number of individuals in the Infectious
#'       disease state.
#'     \item \code{I_mild_count}: The number of individuals in the mild Infectious
#'       disease state.
#'     \item \code{I_hosp_count}: The number of individuals in the severe Infectious
#'       disease state that require hospitalization.
#'     \item \code{R_count}: The number of individuals in the Recovered
#'       (immune) disease state.
#'     \item \code{D_count}: The number of individuals in the Death
#'      state.
#'     \item \code{E_new}: The number of individuals newly transitioning from
#'       Susceptible to Exposed (i.e. new infections) at each timestep.
#'   }
#'
#' When \code{endemic_or_epidemic = "endemic"}, an additional column is included:
#'   \itemize{
#'     \item \code{n_external_infections}: The number of susceptible individuals
#'       infected via the external/background infection source at each timestep.
#'   }
#'
#' When \code{render_diagnostics = TRUE}, additional diagnostic columns are
#' included:
#'   \itemize{
#'     \item \code{FOI_household}: The maximum force of infection from household
#'       contacts across all individuals at each timestep.
#'     \item \code{FOI_workplace}: The maximum force of infection from workplace
#'       contacts across all individuals at each timestep.
#'     \item \code{FOI_school}: The maximum force of infection from school
#'       contacts across all individuals at each timestep.
#'     \item \code{FOI_leisure}: The maximum force of infection from leisure
#'       setting contacts across all individuals at each timestep.
#'     \item \code{FOI_community}: The community-level force of infection
#'       (derived from global prevalence) at each timestep.
#'     \item \code{FOI_total}: The maximum total force of infection (sum across
#'       all settings) experienced by any individual at each timestep.
#'   }
#'
#' @family model
#' @export
run_simulation <- function(parameters_list, state = NULL) {

  # Set the seed from the parameter list:
  if (!("seed" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called seed")
  }
  set.seed(parameters_list$seed)

  # Generate the model variables:
  variables_list <- create_variables(parameters_list)
  parameters_list <- variables_list$parameters_list  # note: this could be written more nicely and in a way
  variables_list <- variables_list$variables_list    #       that doesn't require recursive modification

  # Generate the model events:
  events_list <- create_events(
    variables_list = variables_list,
    parameters_list = parameters_list
  )

  # Set up the model renderer:
  timesteps <- round(parameters_list$simulation_time / parameters_list$dt)
  renderer <- individual::Render$new(timesteps)

  # Generate the model processes:
  processes_list <- create_processes(
    variables_list = variables_list,
    events_list = events_list,
    parameters_list = parameters_list,
    renderer = renderer
  )

  # Use individual::simulation_loop() to run the model for the specified number of timesteps
  final_state <- individual::simulation_loop(
    variables = variables_list,
    events = unlist(events_list),
    processes = processes_list,
    timesteps = timesteps,
    state = state
  )
  list(result = renderer$to_dataframe(), state = final_state)
}

#' Run helios simulations using table of parameter values
#'
#' @param parameters_table A data frame in which each row contains parameter values for helios model parameters (preferably in data.frame() format)
#' @param output_type A character string instructing the function to output the parameters, simulations, or both (default = simulations)
#'
#' @family model
#' @export
#'
run_simulations_from_table <- function(
  parameters_table,
  output_type = "simulations"
) {
  # Check that the parameters_table is a data.frame object:
  if (!is.data.frame(parameters_table)) {
    stop("Error: parameters_table is not a data.frame - please reformat")
  }

  # Check that all parameters in the parameter_table are present in the get_parameters() parameters_list:
  if (!all(names(parameters_table) %in% names(get_parameters()))) {
    stop(
      "Error: Parameter name in parameter_table not a recognised helios parameter"
    )
  }

  # Convert the parameters_table to data.frame format:
  parameters_table <- as.data.frame(parameters_table)

  # Open a list to store the parameter lists:
  parameters_lists <- list()

  # Open a list to store the simulation outputs:
  simulation_outputs <- list()

  # TODO: Add lines to outputs that append the parameters varied to the dataframe:
  for (i in 1:nrow(parameters_table)) {
    # Open a new parameter list for the i-th row of the parameter table:
    parameters_lists[[i]] <- get_parameters()

    # For each column in the parameter table, overwrite the corresponding parameter in the list:
    for (j in 1:ncol(parameters_table)) {
      parameters_lists[[i]][[names(parameters_table[j])]] <- parameters_table[
        i,
        j
      ]
    }

    # Run the simulations if output_type is simulations or both:
    if (output_type %in% c("simulations", "both")) {
      # Run the simulation i-th simulation:
      simulation_outputs[[i]] <- run_simulation(
        parameters_list = parameters_lists[[i]]
      )$result

      # Append the varied parameters as columns:
      simulation_outputs[[i]] <- dplyr::bind_cols(
        simulation_outputs[[i]],
        dplyr::as_tibble(parameters_table[i, ])
      )

      # Print the simulation progress:
      print(paste0(
        "Simulation ",
        i,
        " complete (",
        (i / nrow(parameters_table) * 100),
        "% of simulations complete)"
      ))
    }
  }

  # Determine which objects to return:
  if (output_type == "parameters") {
    return(parameters_lists)
  } else if (output_type == "simulations") {
    return(simulation_outputs)
  } else if (output_type == "both") {
    return(list(parameters_lists, simulation_outputs))
  }
}
