#' Run the simulation
#'
#' @param parameters_list A list of model parameters as generated by [get_parameters()]
#' @param timesteps An integer representing the number of timesteps to simulate
#'
#' @family model
#' @export
run_simulation <- function(parameters_list) {

  # Generate the model variables:
  variables_list <- create_variables(parameters_list)
  parameters_list <- variables_list$parameters_list # note: this could be written more nicely and in a way
  variables_list <- variables_list$variables_list   #       that doesn't require recursive modification

  # Generate the model events:
  events_list <- create_events(variables_list = variables_list, parameters_list = parameters_list)

  # Set up the model renderer:
  timesteps <- round(parameters_list$simulation_time/parameters_list$dt)
  renderer <- individual::Render$new(timesteps)

  # Generate the model processes:
  processes_list <- create_processes(variables_list = variables_list,
                                     events_list = events_list,
                                     parameters_list = parameters_list,
                                     renderer = renderer)

  # Use individual::simulation_loop() to run the model for the specified number of timesteps
  individual::simulation_loop(
    variables = variables_list,
    events = unlist(events_list),
    processes = processes_list,
    timesteps = timesteps
  )
  renderer$to_dataframe()
}


#' Run helios simulations using table of parameter values
#'
#' @param parameters_table A data frame in which each row contains parameter values for helios model parameters
#'
#' @export
#'
run_simulations_from_table <- function(parameters_table) {

  # Open a list to store the parameter lists:
  parameters_lists <- list()


  # Open a list to store the simulation outputs:
  simulation_outputs <- list()


  # TODO: Add lines to outputs that append the parameters varied to the dataframe:
  for(i in 1:nrow(parameters_table)) {

  }

}
