#' Define and create all model processes
#'

#' @param variables_list A list of model variables as generated by [create_variables()]
#' @param events_list A list of the model events as generated by [create_events()]
#' @param parameters_list A list of model parameters as generated by [get_parameters()]
#' @param renderer An individual-package render object
#'
#' @family processes
#' @export
create_processes <- function(
  variables_list,
  events_list,
  parameters_list,
  renderer
) {
  # Open a list of processes to store the model processes in:
  # NOTE: EI_process, IR_process, and RS_process have been replaced by inline
  # event scheduling via listeners in create_events(). Transitions are now
  # scheduled at the point of infection/transition rather than polling every
  # timestep.
  processes_list <- list(
    SE_process = create_SE_process(
      variables_list = variables_list,
      events_list = events_list,
      parameters_list = parameters_list,
      renderer = renderer
    )
  )

  # ===============================
  # ENDEMIC DISEASE MODE
  # ===============================
  if (parameters_list$endemic_or_epidemic == "endemic") {
    processes_list <- c(
      processes_list,
      list(
        external_source_process = create_external_source_process(
          variables_list = variables_list,
          events_list = events_list,
          parameters_list = parameters_list,
          renderer = renderer
        )
      )
    )
  }

  # ===============================
  # Rendering processes
  # ===============================
  # health_render_process
  processes_list <- c(
    processes_list,
    renderer = individual::categorical_count_renderer_process(
      renderer,
      variables_list$disease_state,
      c('S', 'E', 'I', 'R')
    )
  )

  # Return the model processes:
  return(processes_list)
}

#' Create process governing susceptible to exposed disease state transition
#'
#' @inheritParams create_processes
#'
#' @family processes
#' @export
create_SE_process <- function(
  variables_list,
  events_list,
  parameters_list,
  renderer
) {
  ## Pre-calculating the things that only have to be calculated once
  N <- parameters_list$human_population

  ##### HOUSEHOLDS #####
  # Get integer vector mapping each individual to their household ID
  num_households <- parameters_list$num_households
  household_of <- variables_list$household$get_values()
  household_sizes <- tabulate(household_of, nbins = num_households)

  ##### WORKPLACES #####
  # Get integer vector mapping each individual to their workplace ID (0 = not in a workplace)
  num_workplaces <- parameters_list$num_workplaces
  workplace_of <- variables_list$workplace$get_values()
  workplace_sizes <- tabulate(workplace_of, nbins = num_workplaces)

  ##### SCHOOLS #####
  # Get integer vector mapping each individual to their school ID (0 = not in a school)
  num_schools <- parameters_list$num_schools
  school_of <- variables_list$school$get_values()
  school_sizes <- tabulate(school_of, nbins = num_schools)

  ##### EFFECTIVE MULTIPLIERS #####
  # Precompute per-group multiplier: riskiness * beta / group_size
  # Per-timestep FOI for group g = multiplier[g] * num_infected_in_g
  hh_multiplier <- parameters_list$household_specific_riskiness *
    parameters_list$beta_household / household_sizes
  # Match original behaviour: single-person households get zero FOI
  hh_multiplier[household_sizes <= 1] <- 0

  wp_multiplier <- parameters_list$workplace_specific_riskiness *
    parameters_list$beta_workplace / workplace_sizes

  sc_multiplier <- parameters_list$school_specific_riskiness *
    parameters_list$beta_school / school_sizes

  ##### FAR UVC: HOUSEHOLDS #####
  # Precompute two multiplier vectors (pre- and post-UVC activation) and swap once
  if (parameters_list$far_uvc_household) {
    hh_multiplier_pre_uvc <- hh_multiplier
    hh_multiplier_post_uvc <- hh_multiplier
    uvc_groups <- which(parameters_list$uvc_household == 1)
    hh_multiplier_post_uvc[uvc_groups] <- hh_multiplier[uvc_groups] *
      (1 - parameters_list$far_uvc_household_efficacy)
    hh_uvc_timestep <- parameters_list$far_uvc_household_timestep
    hh_uvc_active <- FALSE
  } else {
    hh_multiplier_pre_uvc <- hh_multiplier
    hh_multiplier_post_uvc <- hh_multiplier
    hh_uvc_active <- TRUE  # treat as already activated so we never check
  }
  hh_current_multiplier <- hh_multiplier_pre_uvc

  ##### FAR UVC: WORKPLACES #####
  if (parameters_list$far_uvc_workplace) {
    wp_multiplier_pre_uvc <- wp_multiplier
    wp_multiplier_post_uvc <- wp_multiplier
    uvc_groups <- which(parameters_list$uvc_workplace == 1)
    wp_multiplier_post_uvc[uvc_groups] <- wp_multiplier[uvc_groups] *
      (1 - parameters_list$far_uvc_workplace_efficacy)
    wp_uvc_timestep <- parameters_list$far_uvc_workplace_timestep
    wp_uvc_active <- FALSE
  } else {
    wp_multiplier_pre_uvc <- wp_multiplier
    wp_multiplier_post_uvc <- wp_multiplier
    wp_uvc_active <- TRUE
  }
  wp_current_multiplier <- wp_multiplier_pre_uvc

  ##### FAR UVC: SCHOOLS #####
  if (parameters_list$far_uvc_school) {
    sc_multiplier_pre_uvc <- sc_multiplier
    sc_multiplier_post_uvc <- sc_multiplier
    uvc_groups <- which(parameters_list$uvc_school == 1)
    sc_multiplier_post_uvc[uvc_groups] <- sc_multiplier[uvc_groups] *
      (1 - parameters_list$far_uvc_school_efficacy)
    sc_uvc_timestep <- parameters_list$far_uvc_school_timestep
    sc_uvc_active <- FALSE
  } else {
    sc_multiplier_pre_uvc <- sc_multiplier
    sc_multiplier_post_uvc <- sc_multiplier
    sc_uvc_active <- TRUE
  }
  sc_current_multiplier <- sc_multiplier_pre_uvc

  ##### LEISURE SETUP #####
  # Build a 7 x N matrix of possible leisure visits
  # Each column is one individual's 7-day pattern (0 = stay home)
  leisure_possible <- matrix(0L, nrow = 7, ncol = N)
  for (i in seq(N)) {
    leisure_possible[, i] <- as.integer(
      unlist(variables_list$leisure$get_values(i))
    )
  }

  # Plain integer vector for today's leisure assignment (updated daily)
  leisure_today <- integer(N)

  # Handle non-contiguous leisure IDs
  actual_leisure_ids <- sort(
    parameters_list$leisure_indices[parameters_list$leisure_indices > 0]
  )
  num_leisure <- length(actual_leisure_ids)
  max_leisure_id <- max(actual_leisure_ids)

  # Build lookup: le_riskiness_beta[original_id] = riskiness * beta
  # The denominator (visitor count) is computed dynamically each day to match original semantics
  le_riskiness_beta_lookup <- numeric(max_leisure_id)
  le_riskiness_beta_lookup[actual_leisure_ids] <-
    parameters_list$leisure_specific_riskiness * parameters_list$beta_leisure

  # Initialise visitor count vectors (updated daily within the closure)
  le_visitor_counts <- integer(max_leisure_id)
  le_safe_visitors <- rep(1L, max_leisure_id)

  ##### FAR UVC: LEISURE #####
  if (parameters_list$far_uvc_leisure) {
    le_rb_pre_uvc <- le_riskiness_beta_lookup
    le_rb_post_uvc <- le_riskiness_beta_lookup
    uvc_leisure_groups <- which(parameters_list$uvc_leisure == 1)
    uvc_leisure_ids <- actual_leisure_ids[uvc_leisure_groups]
    le_rb_post_uvc[uvc_leisure_ids] <-
      le_riskiness_beta_lookup[uvc_leisure_ids] *
      (1 - parameters_list$far_uvc_leisure_efficacy)
    le_uvc_timestep <- parameters_list$far_uvc_leisure_timestep
    le_uvc_active <- FALSE
  } else {
    le_rb_pre_uvc <- le_riskiness_beta_lookup
    le_rb_post_uvc <- le_riskiness_beta_lookup
    le_uvc_active <- TRUE
  }
  le_current_rb <- le_rb_pre_uvc

  ## Process Function
  function(t) {

    ## UVC activation (each block runs at most once across the simulation)
    if (!hh_uvc_active && t > hh_uvc_timestep) {
      hh_current_multiplier <<- hh_multiplier_post_uvc
      hh_uvc_active <<- TRUE
    }
    if (!wp_uvc_active && t > wp_uvc_timestep) {
      wp_current_multiplier <<- wp_multiplier_post_uvc
      wp_uvc_active <<- TRUE
    }
    if (!sc_uvc_active && t > sc_uvc_timestep) {
      sc_current_multiplier <<- sc_multiplier_post_uvc
      sc_uvc_active <<- TRUE
    }
    if (!le_uvc_active && t > le_uvc_timestep) {
      le_current_rb <<- le_rb_post_uvc
      le_uvc_active <<- TRUE
    }

    ## Get indices of all currently infected individuals
    I <- variables_list$disease_state$get_index_of("I")
    I_vec <- I$to_vector()
    num_infected <- length(I_vec)

    #=== Household FOI ===#
    # Count infected per household, compute per-group FOI, gather to per-individual
    hh_I_counts <- tabulate(household_of[I_vec], nbins = num_households)
    hh_group_foi <- hh_current_multiplier * hh_I_counts
    household_FOI <- hh_group_foi[household_of]

    #=== Workplace FOI ===#
    # Prepend 0 and shift indices by 1 to handle workplace_of == 0 (unassigned)
    wp_I_counts <- tabulate(workplace_of[I_vec], nbins = num_workplaces)
    wp_group_foi <- c(0, wp_current_multiplier * wp_I_counts)
    workplace_FOI <- wp_group_foi[workplace_of + 1L]

    #=== School FOI ===#
    # Same zero-handling pattern as workplaces
    sc_I_counts <- tabulate(school_of[I_vec], nbins = num_schools)
    sc_group_foi <- c(0, sc_current_multiplier * sc_I_counts)
    school_FOI <- sc_group_foi[school_of + 1L]

    #=== Leisure FOI ===#
    # Daily reassignment (only on whole-day boundaries)
    if ((t * parameters_list$dt) == floor(t * parameters_list$dt)) {
      day_indices <- dqrng::dqsample.int(n = 7, size = N, replace = TRUE)
      leisure_today <<- leisure_possible[cbind(day_indices, seq_len(N))]
      # Compute visitor counts for the day (used as denominator in FOI)
      le_visitor_counts <<- tabulate(leisure_today, nbins = max_leisure_id)
      le_safe_visitors <<- pmax(le_visitor_counts, 1L)
    }

    # Count infected per leisure venue (tabulate ignores 0s automatically)
    le_I_counts <- tabulate(leisure_today[I_vec], nbins = max_leisure_id)

    # Compute per-venue FOI: riskiness * beta * I_count / visitor_count
    le_group_foi <- le_current_rb * le_I_counts / le_safe_visitors

    # Gather to per-individual, handling leisure_today == 0 (not visiting)
    le_group_foi_shifted <- c(0, le_group_foi)
    leisure_FOI <- le_group_foi_shifted[leisure_today + 1L]

    #=== Community FOI ===#
    community_FOI <- parameters_list$beta_community * num_infected / N

    #=== Total FOI ===#
    total_FOI <- household_FOI +
      workplace_FOI +
      school_FOI +
      leisure_FOI +
      community_FOI

    # Render the setting-specific FOIs if diagnostic rendering turned on:
    if (parameters_list$render_diagnostics) {
      renderer$render('FOI_household', max(household_FOI), t)
      renderer$render('FOI_workplace', max(workplace_FOI), t)
      renderer$render('FOI_school', max(school_FOI), t)
      renderer$render('FOI_leisure', max(leisure_FOI), t)
      renderer$render('FOI_community', max(community_FOI), t)
      renderer$render('FOI_total', max(total_FOI), t)
    }

    # Calculate the probability of getting infected in the current interval for each individual:
    p_inf <- 1 - exp(-total_FOI * parameters_list$dt)

    # Get the indices of all susceptible individuals in the current timestep:
    S <- variables_list$disease_state$get_index_of("S")

    # Get the infection probability for each currently susceptible individual:
    p_inf_currently_S <- p_inf[S$to_vector()]

    # Sample susceptible individuals using their infection probability to determine who gets infected:
    S$sample(rate = p_inf_currently_S)

    # Render the number of people going from susceptible to infected:
    renderer$render('E_new', S$size(), t)

    # Queue an update to the infectious state of the newly infected susceptible individuals to Exposed:
    variables_list$disease_state$queue_update(value = "E", index = S)

    # Schedule the E->I transition inline (replaces EI_process)
    if (S$size() > 0) {
      I_times <- round(
        (rgamma(
          n = S$size(),
          shape = 2,
          rate = 2 / parameters_list$duration_exposed
        ) + 1) /
          parameters_list$dt
      )
      events_list$EI_event$schedule(target = S, delay = I_times)
    }
  }
}


#' Create process governing exposed to infectious disease state transition
#'
#' @inheritParams create_processes
#'
#' @family processes
#' @export
create_EI_process <- function(variables_list, events_list, parameters_list) {
  function(t) {
    # Get the indices of all exposed individuals:
    E <- variables_list$disease_state$get_index_of("E")

    # Get the indices of exposed individuals for which transitions to I have been scheduled:
    EI_already_scheduled <- events_list$EI_event$get_scheduled()

    # Get the indices of all exposed individuals with progression to I already scheduled:
    E$and(EI_already_scheduled$not(inplace = TRUE))

    # Calculate the delay until each exposed individual without a delay transitions to infected:
    I_times <- round(
      (rgamma(
        n = E$size(),
        shape = 2,
        rate = 2 / parameters_list$duration_exposed
      ) +
        1) /
        parameters_list$dt
    )

    # Schedule the new transitions from exposed to infected:
    events_list$EI_event$schedule(target = E, delay = I_times)
  }
}

#' Create process governing infectious to recovered disease state transition
#'
#' @inheritParams create_processes
#'
#' @family processes
#' @export
create_IR_process <- function(variables_list, events_list, parameters_list) {
  function(t) {
    # Get the indices of currently infectious individuals:
    I <- variables_list$disease_state$get_index_of("I")

    # Get the indices of individuals with I to R transitions already scheduled:
    IR_already_scheduled <- events_list$IR_event$get_scheduled()

    # Get the indices of infectious individuals without I to R transitions already scheduled:
    I$and(IR_already_scheduled$not(inplace = TRUE))

    # Calculate recovery times for infectious individuals without transitions scheduled:
    R_times <- round(
      (rgamma(
        n = I$size(),
        shape = 2,
        rate = 2 / parameters_list$duration_infectious
      ) +
        1) /
        parameters_list$dt
    )

    # Schedule the recovery events for infectious individuals without transitions scheduled:
    events_list$IR_event$schedule(target = I, delay = R_times)
  }
}

#' Create process governing recovered (and immune) back to susceptible disease state transition
#'
#' @inheritParams create_processes
#'
#' @family processes
#' @export
create_RS_process <- function(variables_list, events_list, parameters_list) {
  function(t) {
    # Get the indices of currently recovered and immune individuals:
    R <- variables_list$disease_state$get_index_of("R")

    # Get the indices of individuals with I to R transitions already scheduled:
    RS_already_scheduled <- events_list$RS_event$get_scheduled()

    # Get the indices of infectious individuals without R to S transitions already scheduled:
    R$and(RS_already_scheduled$not(inplace = TRUE))

    # Calculate recovery times for infectious individuals without transitions scheduled:
    S_times <- round(
      rgamma(
        n = R$size(),
        shape = 1,
        rate = 1 / parameters_list$duration_immune
      ) /
        parameters_list$dt
    )

    # Schedule the recovery events for infectious individuals without transitions scheduled:
    events_list$RS_event$schedule(target = R, delay = S_times)
  }
}

#' Create process governing exposed to infectious disease state transition
#'
#' @inheritParams create_processes
#'
#' @family processes
#' @export
create_external_source_process <- function(
  variables_list,
  events_list,
  parameters_list,
  renderer
) {
  function(t) {
    # Get the indices of all susceptible individuals:
    S_endemic <- variables_list$disease_state$get_index_of("S")

    # Calculate the probability of getting infected in the current interval for each individual:
    p_inf_ext <- 1 -
      exp(-parameters_list$prob_inf_external * parameters_list$dt)

    # Sample susceptible individuals using their infection probability to determine who gets infected:
    S_endemic$sample(rate = p_inf_ext)

    # Queue an update to the infectious state of the newly infected susceptible individuals to Exposed:
    variables_list$disease_state$queue_update(value = "E", index = S_endemic)

    # Schedule the E->I transition inline (replaces EI_process)
    if (S_endemic$size() > 0) {
      I_times <- round(
        (rgamma(
          n = S_endemic$size(),
          shape = 2,
          rate = 2 / parameters_list$duration_exposed
        ) + 1) /
          parameters_list$dt
      )
      events_list$EI_event$schedule(target = S_endemic, delay = I_times)
    }

    # Render the number of individuals infected through the external mechanism
    renderer$render('n_external_infections', S_endemic$size(), t)
  }
}
