# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
bitset_and_size <- function(a, b) {
    .Call('_helios_bitset_and_size', PACKAGE = 'helios', a, b)
}

