#' Generate per-location baseline ACH values for a setting
#'
#' @description
#' Returns a numeric vector of length `number_of_locations` giving the
#' baseline ACH (air changes per hour) for each location in `setting`.
#'
#' Three branches, depending on how the user has configured ACH for the
#' setting:
#' * If `setting_specific_ach_<setting>` is TRUE (via
#'   [set_setting_specific_ach()]) — draws per-location ACH from a truncated
#'   normal distribution with the configured mean and sd. Heterogeneous case.
#' * Else if `default_ach_<setting>` is non-NULL (via [set_default_ach()]) —
#'   returns the same value at every location. Uniform case.
#' * Else — errors out. There is no silent default; the user must explicitly
#'   choose one of the two paths above to prevent unconfigured baselines
#'   producing spurious intervention efficacy downstream.
#'
#' Called once per setting during [create_variables()] init. The returned
#' vector is stored at `<setting>_specific_ach` in `parameters_list` and is
#' subsequently consumed by [convert_ach_to_riskiness()] and (when an
#' intervention is active) by [calculate_efficacy_from_ach()].
#'
#' @param parameters_list A list of model parameters as generated by
#' [get_parameters()].
#' @param setting Character. One of `"workplace"`, `"school"`, `"leisure"`,
#' or `"household"`.
#' @param number_of_locations Integer. Number of locations in the setting
#' (determined from `variables_list` upstream).
#'
#' @return Numeric vector of length `number_of_locations` containing the
#' per-location baseline ACH values (1/hour).
#'
#' @family setting-specific ACH

generate_setting_specific_ach <- function(parameters_list, setting, number_of_locations) {
  # If setting-specific ACH is switched off, fall back to a uniform ACH at
  # default_ach_<setting>. If the user hasn't set that either, error out —
  # there is no silent default, to prevent accidental high-efficacy
  # interventions against an unconfigured baseline.
  if (!isTRUE(parameters_list[[paste0("setting_specific_ach_", setting)]])) {
    default <- parameters_list[[paste0("default_ach_", setting)]]
    if (is.null(default)) {
      stop(
        "ACH for the ", setting, " setting has not been configured. ",
        "Call set_setting_specific_ach('", setting, "', mean = ..., sd = ...) ",
        "for a heterogeneous distribution, or set_default_ach('", setting,
        "', ach = ...) for a uniform value."
      )
    }
    return(rep(default, number_of_locations))
  }

  #retrieve mean and sd values from parameters.R or user input
  mu <- parameters_list[[paste0("setting_specific_ach_", setting, "_mean")]]
  sigma <- parameters_list[[paste0("setting_specific_ach_", setting, "_sd")]]

  #Draw values from truncated normal distribution
  ach_values <- truncnorm::rtruncnorm(n = number_of_locations, a = 0, b = Inf, mean = mu, sd = sigma)

  return(ach_values)
}

#' Convert per-location ACH values to per-location riskiness
#'
#' @description
#' Applies the Wells-Riley framework to convert each location's baseline ACH
#' into a relative riskiness value (a per-location multiplier on the FOI).
#'
#' For each location `i`:
#' \deqn{p_{inf}(i) = 1 - \exp(-r \cdot C_{ss}(i) \cdot RR_{tv} \cdot t)}
#' \deqn{C_{ss}(i) = (I \cdot \pi) / (\alpha_i \cdot V), \quad \alpha_i = ACH_i + k_D}
#'
#' Riskiness is then normalised so a typical location has value 1:
#' \deqn{riskiness_i = p_{inf}(i) / p_{inf}(ACH_{median})}
#'
#' Because the Wells-Riley exponent is small for our parameter values,
#' `1 - exp(-x) \approx x`, and the cancellation simplifies riskiness to
#' approximately `(ACH_ref + kD) / (ACH_i + kD)` — i.e., it depends only on
#' ACH. The constants `I`, `pi`, `RR_tv`, `t`, and `V` cancel.
#'
#' Called once per setting during [create_variables()] init, immediately
#' after [generate_setting_specific_ach()]. The result is stored at
#' `<setting>_specific_riskiness` and used by `processes.R` to scale the
#' per-setting FOI.
#'
#' @param ach_values Numeric vector of per-location baseline ACH values
#' (1/hour), as returned by [generate_setting_specific_ach()].
#' @param parameters_list A list of model parameters as generated by
#' [get_parameters()]. The Wells-Riley parameters
#' (`wells_riley_emission_rate`, `wells_riley_decay_rate`,
#' `wells_riley_infection_prob_per_ffu`,
#' `wells_riley_respiratory_rate_factor`, `wells_riley_time_in_room`) and
#' the setting volume (`volume_per_person_<setting>`) are read from here.
#' @param setting Character. One of `"workplace"`, `"school"`, `"leisure"`,
#' or `"household"`. Used to select the appropriate `volume_per_person_*`.
#'
#' @return Numeric vector of per-location riskiness values, same length as
#' `ach_values`, anchored so the median location has riskiness ~ 1.
#'
#' @family setting-specific ACH
convert_ach_to_riskiness <- function(ach_values, parameters_list, setting) {
  # W-R parameters from parameters_list in parameters.R
  I <- 1
  pi <- parameters_list$wells_riley_emission_rate
  kD <- parameters_list$wells_riley_decay_rate
  r <- parameters_list$wells_riley_infection_prob_per_ffu
  RRtv <- parameters_list$wells_riley_respiratory_rate_factor
  t <- parameters_list$wells_riley_time_in_room

  volume_per_person <- parameters_list[[paste0("volume_per_person_", setting)]]

  # alpha values
  alpha_values <- ach_values + kD

  # steady-state concentration (per-person volume, density-based)
  Css_values <- (I * pi) / (alpha_values * volume_per_person)

  # p(infection)
  p_inf_values <- 1 - exp(-r * Css_values * RRtv * t)

  # reference p_inf for normalization: anchor riskiness at the setting's
  # median ACH, so the typical location has riskiness ~ 1.
  ach_ref <- median(ach_values)
  alpha_ref <- ach_ref + kD
  Css_ref <- (I * pi) / (alpha_ref * volume_per_person)
  p_inf_ref <- 1 - exp(-r * Css_ref * RRtv * t)

  # relative riskiness
  riskiness <- p_inf_values / p_inf_ref

  return(riskiness)
}

#' Set ACH distribution for a setting type
#'
#' @description
#' Activates setting-specific ACH for a single setting and configures the
#' truncated-normal distribution from which each location's baseline ACH is
#' drawn. Per-location ACH values feed into both the riskiness calculation
#' (via [convert_ach_to_riskiness()]) and any intervention efficacy
#' calculation (via [calculate_efficacy_from_ach()]).
#'
#' @param parameters_list A list of model parameters as generated by
#' [get_parameters()].
#' @param setting Character. One of `"workplace"`, `"school"`, `"leisure"`,
#' or `"household"`.
#' @param mean Mean of the truncated normal ACH distribution (1/hour).
#' @param sd Standard deviation of the truncated normal ACH distribution
#' (1/hour).
#'
#' @return The input `parameters_list` with the setting's switch turned on
#' and the mean/sd populated.
#'
#' @family setting-specific ACH
#' @export
set_setting_specific_ach <- function(parameters_list, setting, mean, sd) {
  parameters_list[[paste0("setting_specific_ach_", setting)]]        <- TRUE
  parameters_list[[paste0("setting_specific_ach_", setting, "_mean")]] <- mean
  parameters_list[[paste0("setting_specific_ach_", setting, "_sd")]]   <- sd

  return(parameters_list)
}

#' Set a uniform default ACH for a setting type
#'
#' @description
#' Configures a single setting so that every location in it has the same
#' baseline ACH. This is the "uniform" alternative to
#' [set_setting_specific_ach()], which draws per-location ACH values from a
#' distribution.
#'
#' Sets the package parameter `default_ach_<setting>` to `ach`. Because the
#' setting-specific switch stays FALSE, the model treats this setting as
#' "no per-location variation" — every location in the setting gets ACH equal
#' to `ach`.
#'
#' For every setting used in a simulation, the user must call either
#' [set_setting_specific_ach()] (distribution) or [set_default_ach()]
#' (uniform); otherwise `create_variables()` will error.
#'
#' @param parameters_list A list of model parameters as generated by
#' [get_parameters()].
#' @param setting Character. One of `"workplace"`, `"school"`, `"leisure"`,
#' or `"household"`.
#' @param ach Numeric. The uniform ACH value assigned to every location in
#' the setting (1/hour). Must be non-negative.
#'
#' @return The input `parameters_list` with `default_ach_<setting>` set to
#' `ach`.
#'
#' @family setting-specific ACH
#' @export
set_default_ach <- function(parameters_list, setting, ach) {
  if (!(setting %in% c("workplace", "school", "leisure", "household"))) {
    stop("setting must be one of 'workplace', 'school', 'leisure', 'household'")
  }
  if (!is.numeric(ach) || length(ach) != 1 || ach < 0) {
    stop("ach must be a single non-negative numeric value")
  }
  parameters_list[[paste0("default_ach_", setting)]] <- ach
  parameters_list
}

