#' Generate a list of the model variables
#'
#' @param parameters - A list of model parameters as generated by `get_parameters`
#'
#' @export
create_variables <- function(parameters) {

  # Initialise and populate the disease state variable:
  disease_states <- c("S", "E", "I", "R")
  initial_disease_states <- generate_initial_disease_states(parameters)
  disease_state_variable <- individual::CategoricalVariable$new(categories = disease_states,
                                                                initial_values = initial_disease_states)

  # Initialise and populate the age class variable:
  age_classes <- c("child", "adult", "elderly")
  initial_age_classes <- generate_initial_age_classes(parameters = parameters)
  age_class_variable <- individual::CategoricalVariable$new(categories = age_classes,
                                                            initial_values = initial_age_classes)

  # Initialise and populate the workplace setting variable:
  initial_workplace_settings <- generate_initial_workplaces(parameters = parameters, age_class_variable = age_class_variable)
  num_workplaces <- max(as.numeric(initial_workplace_settings))
  workplace_variable <- CategoricalVariable$new(categories = as.character(0:num_workplaces),
                                                initial_values = initial_workplace_settings)

  # Initialise and populate the school setting variable:
  initial_school_settings <- generate_initial_schools(parameters = parameters, age_class_variable = age_class_variable)
  school_variable <- CategoricalVariable$new(categories = as.character(0:parameters$num_schools), ## change this to be the maximum of as.numeric(initial_school_settings) when proper function is in
                                             initial_values = initial_school_settings)

  # Initialise and populate the household variable
  initial_households <- generate_initial_households(parameters = parameters, age_class_variable = age_class_variable)
  household_variable <- CategoricalVariable$new(categories = as.character(1:max(initial_households)),
                                                initial_values = as.character(initial_households))

  # Store the model variables in a single list:
  variables <- list(
    disease_state = disease_state_variable,
    age_class = age_class_variable,
    workplace = workplace_variable,
    school = school_variable,
    household = household_variable
    )

  # Return the list of model variables:
  return(variables)

}

#' Generate a vector of the initial disease states of all individuals in the population
#'
#' @param parameters A list of model parameters as generated by `get_parameters`
#'
#' @export
generate_initial_disease_states <- function(parameters) {

  # Checking that the parameters contain the initial human population size, proportion
  # initially exposed, and a seed:
  if (!("number_initially_exposed" %in% names(parameters))) {
    stop("parameters list must contain a variable called number_initially_exposed")
  }
  if (!("human_population" %in% names(parameters))) {
    stop("parameters list must contain a variable called human_population")
  }
  if (!("seed" %in% names(parameters))) {
    stop("parameters list must contain a variable called seed")
  }

  # Set the seed from the parameter list:
  set.seed(parameters$seed)

  # Create a vector of disease states of length human_population:
  initial_disease_states <- rep("S", parameters$human_population)

  # Sample indices between 1:human population to set an initially exposed:
  infection_index <- sample(x = 1:length(initial_disease_states),
                            size = parameters$number_initially_exposed,
                            replace = FALSE,
                            prob = NULL)

  # Replace the disease state at the sampled indices with to "E" (Exposed)
  initial_disease_states[infection_index] <- "E"

  # Return the vector of initial disease states:
  return(initial_disease_states)

}

#' Generates a vector of the age classes of all individuals in the population
#'
#' @param parameters A list of model parameters as generated by `get_parameters`
#'
#' @export
generate_initial_age_classes <- function(parameters) {

  # Check the parameters required are present in the parameters list:
  if (!("initial_proportion_child" %in% names(parameters))) {
    stop("parameters list must contain a variable called initial_proportion_child")
  }
  if (!("initial_proportion_adult" %in% names(parameters))) {
    stop("parameters list must contain a variable called initial_proportion_adult")
  }
  if (!("initial_proportion_elderly" %in% names(parameters))) {
    stop("parameters list must contain a variable called initial_proportion_elderly")
  }
  if (!("human_population" %in% names(parameters))) {
    stop("parameters list must contain a variable called human_population")
  }
  if (!("seed" %in% names(parameters))) {
    stop("parameters list must contain a variable called seed")
  }

  # Check the initial age class proportions sum to 1:
  if (sum(parameters$initial_proportion_child, parameters$initial_proportion_adult, parameters$initial_proportion_elderly) != 1) {
    stop("initial age class proportions do not sum to 1")
  }

  # Set the seed stored in the parameter list:
  set.seed(parameters$seed)

  # Store age group proportions in a single vector:
  age_group_proportions <- c(parameters$initial_proportion_child,
                             parameters$initial_proportion_adult,
                             parameters$initial_proportion_elderly)

  # Use the initial age class proportions to sample and create a vector of initial age classes:
  age_classes <- sample(c("child", "adult", "elderly"),
                        size = parameters$human_population,
                        replace = TRUE,
                        prob = age_group_proportions)

  # Return the vector of initial age classes:
  return(age_classes)

}

#' Gets workplace assignments for all individuals in the population
#'
#' @param parameters A list of model parameters as generated by `get_parameters`
#' @param age_class_variable An `individual::CategoricalVariable` for the age classes
#'
#' @export
generate_initial_workplaces <- function(parameters, age_class_variable) {

  # Checking that the parameter list contains the requisite parameters
  if (!("human_population" %in% names(parameters))) {
    stop("parameters list must contain a variable called human_population")
  }
  if (!("seed" %in% names(parameters))) {
    stop("parameters list must contain a variable called seed")
  }
  if (!("workplace_prop_max" %in% names(parameters))) {
    stop("parameters list must contain a variable called workplace_prop_max")
  }
  if (!("workplace_a" %in% names(parameters))) {
    stop("parameters list must contain a variable called workplace_a")
  }
  if (!("workplace_c" %in% names(parameters))) {
    stop("parameters list must contain a variable called workplace_c")
  }

  # Calculating number of adults and assigning them to workplaces
  set.seed(parameters$seed)
  num_adults <- age_class_variable$get_size_of("adult") # get number of adults
  index_adults <- age_class_variable$get_index_of("adult")$to_vector() # get the index of adults in age_class_variable
  workplace_sizes <- sample_offset_truncated_power_distribution(N = num_adults,
                                                                prop_max = parameters$workplace_prop_max,
                                                                a = parameters$workplace_a,
                                                                c = parameters$workplace_c)
  workplace_indices <- unlist(sapply(1:length(workplace_sizes), function(i) rep(as.character(i), workplace_sizes[i])))
  adult_workplace_assignments <- sample(workplace_indices, replace = FALSE)

  # Creating a vector containing workplace assignments for all individuals (i.e. adult_workplace_assignments for adults,
  # 0 for children and elderly)
  workplace_vector <- vector(mode = "character", length = parameters$human_population) # create an empty vector to be filled with workplace assignments
  workplace_vector[index_adults] <- adult_workplace_assignments # append workplace assignments to main workplaces vector
  workplace_vector[workplace_vector == ""] <- "0" # replace blanks with 0s (these are children/elderly people)

  return(workplace_vector)
}

# Function that generates the school assignments for all individuals in the system:
## THIS IS JUST A PLACEHOLDER FOR THE REAL THING
generate_initial_schools <- function(parameters, age_class_variable) {

  ## Replace this with a test to check the relevant parameters are held in the parameters list
  ## E.g. N, school size distribution parameters etc
  # Check that the requisite parameters are present:
  if (!("human_population" %in% names(parameters))) {
    stop("parameters list must contain a variable called human_population")
  }
  if (!("seed" %in% names(parameters))) {
    stop("parameters list must contain a variable called seed")
  }
  if (!("num_schools" %in% names(parameters))) {
    stop("parameters list must contain a variable called num_schools")
  }

  ## Note the below is wrong and just a placeholder - I don't think we want to fix the number of
  ## schools manually, instead let it be a function of the distribution of workplace sizes and the population size

  ## Calculating number of adults and assigning them to workplaces
  set.seed(parameters$seed)
  num_children <- age_class_variable$get_size_of("child") # get number of children
  index_children <- age_class_variable$get_index_of("child")$to_vector() # get the index of children in age_class_variable
  child_school_assignments <- sample(x = as.character(1:parameters$num_schools),
                                     size = length(index_children),
                                     replace = TRUE,
                                     prob = NULL) # randomly sample schools for each child

  ## Creating a vector containing school assignments for all individuals (i.e. child_school_assignments for children,
  ## 0 for adults and elderly)
  schools_vector <- vector(mode = "character", length = parameters$human_population) # create empty vector to be filled with school assignments
  schools_vector[index_children] <- child_school_assignments # append school assignment to main schools vector
  schools_vector[schools_vector == ""] <- "0" # replace blanks with 0s (these are adults/elderly people)

  return(schools_vector)

}

#' Generates a vector of households for all individuals in the population
#'
#' @param parameters A list of model parameters as generated by `get_parameters`
#' @param age_class_variable An `individual::CategoricalVariable` for the age classes
#'
#' @export
generate_initial_households <- function(parameters, age_class_variable) {

  # Check that the requisite parameters are present:
  if (!("human_population" %in% names(parameters))) {
    stop("parameters list must contain a variable called human_population")
  }
  if (!("seed" %in% names(parameters))) {
    stop("parameters list must contain a variable called seed")
  }
  if (!("mean_household_size" %in% names(parameters))) {
    stop("parameters list must contain a variable called mean_household_size")
  }

  # Setting seed
  set.seed(parameters$seed)

  ## Checking population size N is the same as implied by age_class_variable
  if (parameters$human_population != age_class_variable$get_size_of(age_class_variable$get_categories())) {
    stop("Human population and age_class_vector are different lengths")
  }

  ## Extracting out the vector of underlying values from age_class_variable
  age_class_vector <- rep("", parameters$human_population)
  age_class_vector[age_class_variable$get_index_of("child")$to_vector()] <- "child"
  age_class_vector[age_class_variable$get_index_of("adult")$to_vector()] <- "adult"
  age_class_vector[age_class_variable$get_index_of("elderly")$to_vector()] <- "elderly"

  ## Track which individuals are assigned
  assigned <- rep(FALSE, parameters$human_population)
  individual_households <- rep(NA, parameters$human_population)
  household_counter <- 1

  ## Looping over this whilst there still remain any unassigned individuals
  while(sum(assigned) < parameters$human_population) {

    # Check if only children are left unassigned - if this is the case, then we just distribute
    # them randomly across households
    unassigned_indices <- which(!assigned)
    if(all(age_class_vector[unassigned_indices] == "child")) {
      # Distribute remaining children across existing households randomly
      for(child_idx in unassigned_indices) {
        selected_household <- sample(household_counter, 1)
        assigned[child_idx] <- TRUE
        individual_households[child_idx] <- selected_household
      }
      break # Exit the main loop as all remaining unassigned individuals are children and have been assigned
    }

    # Draw household size
    household_size <- rpois(n = 1, lambda = parameters$mean_household_size)

    # Initialize temporary household storage
    temp_household <- c()

    ## Looping over this whilst current household isn't full
    while(length(temp_household) < household_size && sum(assigned) < parameters$human_population) {

      # Randomly select an unassigned individual
      candidates <- which(!assigned)
      selected <- sample(x = candidates, size = 1)

      # Ensure selected individual meets the household formation criteria (i.e. children have to have at least 1 adult in household)
      if(age_class_vector[selected] == "child") {

        ## Check whether current household has an adult - if it does, just add the child
        if(sum(age_class_vector[temp_household] == "adult") >= 1) {
          temp_household <- c(temp_household, selected)
          assigned[selected] <- TRUE
        } else { # if not, get an adult to be added to the household
          # Ensure there is at least one unassigned adult to pair with
          unassigned_adults <- which(age_class_vector == "adult" & !assigned)
          if(length(unassigned_adults) < 1) {
            # No available adults to pair with the child, break from the inner loop
            break
          }
          # Pair child with adult(s)
          num_adults_to_add <- 1
          adults_to_add <- sample(unassigned_adults, num_adults_to_add)
          temp_household <- c(temp_household, selected, adults_to_add)
          assigned[c(selected, adults_to_add)] <- TRUE
        }

      } else {
        # Add the individual to the household if there's enough space
        if((length(temp_household) + 1) <= household_size) {
          temp_household <- c(temp_household, selected)
          assigned[selected] <- TRUE
        }
      }
    }
    # Add the completed household to the list of households, if any members were added
    if(length(temp_household) > 0) {
      individual_households[temp_household] <- household_counter
      household_counter <- household_counter + 1
    }
  }

  return(individual_households = individual_households)
}
